# Generated by Django 2.1.7 on 2019-03-27 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('author', models.CharField(max_length=48)),
                ('year', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in', 'Checked-In'), ('out', 'Checked-Out')], default='in', max_length=48)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('last_borrowed', models.DateField(auto_now=True)),
            ],
        ),
    ]
